FROM debian:latest

RUN apt-get update && \
    apt-get install -y fail2ban iptables && \
    rm -rf /var/lib/apt/lists/*

COPY ./fail2ban/jail.local /etc/fail2ban/jail.local
COPY ./fail2ban/filter.d/nginx-forbidden.conf /etc/fail2ban/filter.d/nginx-forbidden.conf
COPY ./fail2ban/action.d/bash.conf /etc/fail2ban/action.d/bash.conf

CMD ["fail2ban-server", "-f"]
