FROM nginx:latest

RUN apt-get update && apt-get install -y inotify-tools
COPY nginx.conf /etc/nginx/nginx.conf
COPY blocked_urls.conf /etc/nginx/blocked_urls.conf
COPY forbidden_requests.log /var/log/nginx/forbidden_requests.log
COPY fail2ban_redirect.conf /etc/nginx/fail2ban_redirect.conf

COPY monitor.sh /usr/local/bin/monitor.sh

RUN chmod +x /usr/local/bin/monitor.sh

CMD bash -c "nohup /usr/local/bin/monitor.sh & nginx -g 'daemon off;'"
